dist: xenial   # required for Python >= 3.7
language: python

sudo: required
dist: trusty

python:
  - "3.6"
  - "3.7"

git:
  submodules: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - gdal-bin
      - libgdal-dev
      - devscripts
      - fakeroot
      - debhelper
      - python-setuptools

# Handle Git submodules yourself
git:
    submodules: false

env:
  - PYWPS_CFG="$TRAVIS_BUILD_DIR/tests/test-pywps.cfg"

install:
  - pip install pip --upgrade
  - pip install -r requirements.txt
  - pip install -r requirements-gdal.txt
  - pip install -r requirements-extra.txt
  - pip install -r requirements-dev.txt
  - pip install coveralls
  - pip install -e .
  - pywps -c $PYWPS_CFG migrate

script:
  - python -m unittest tests
  - coverage run --source=pywps -m unittest tests
  - flake8 pywps/

after_success:
  - coveralls
  - python setup.py sdist bdist_wheel --universal
  - debuild -b -uc -us

# whitelist
# branches:
#   only:
#     - master

# notifications:
#  irc:
#    channels:
#      - "irc.freenode.org#geopython"
